version: '3.8'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/data:/data
