export const ERR_USER_NOT_FOUND = 1001
export const ERR_USER_ALREADY_EXISTS = 1002
export const ERR_USER_UNBOUND = 1003
export const ERR_USER_PASSWORD_UPDATE = 1004
export const ERR_USER_INFO_UPDATE = 1005
export const ERR_USER_REGISTER = 1006
export const ERR_USERNAME_EXISTED = 1007
export const ERR_BIND = 1008
export const ERR_EXISTED = 1009

export const ERR_CREDENTIALS_INVALID = 1010
export const ERR_PERMISSIONS_INSUFFICIENT = 1011
export const ERR_CODE_INVALID = 1012
export const ERR_AUTHORIZATION = 1013
export const ERR_INTERNAL_OAUTH = 1014

export const ERR_CAPTCHA_EXPIRES = 1015
export const ERR_CAPTCHA_INVALID = 1016

export const ERR_PHONE_BIND = 2001

export const ERR_FILE_SIZE_LIMIT_EXCEEDED = 3001
export const ERR_UNSUPPORTED_FILE_FORMAT = 3002

export const ERR_DELETE = 5001
